# permissions for end users to view loadtests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: loadtest-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: go-load-test-controller
    app.kubernetes.io/part-of: go-load-test-controller
    app.kubernetes.io/managed-by: kustomize
  name: loadtest-viewer-role
rules:
- apiGroups:
  - platform.mycompany.com
  resources:
  - loadtests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.mycompany.com
  resources:
  - loadtests/status
  verbs:
  - get
